# -*- coding: utf-8 -*-
"""Feature_selection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11bbTKXAFNeY2BQ2elZWPM-2yH1yWRrfA

**Dropping Const Features**
"""

import pandas as pd

data = pd.DataFrame({'A':[1,2,3,4,5,6],
                     'B':[1,22,34,4,15,6],
                     'C':[0,0,0,0,0,0],
                     'D':[1,1,1,1,1,1]})

data.head()

"""***VarianceThreshold*** from sklearn"""

from sklearn.feature_selection import VarianceThreshold
v = VarianceThreshold(threshold=0)
v.fit(data)
VarianceThreshold(threshold=0)

v.get_support()

data.columns[v.get_support()]

c = [column for column in data.columns if column not in data.columns[v.get_support()]]
print(len(c))

for i in c:
  print(i)

data.drop(c, axis=1)

"""**Feature Engineering**"""

